#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

GIT_SHA=$(git rev-parse HEAD)
export E2E_IMAGE="gcr.io/coreos-k8s-scale-testing/cliente2e:${GIT_SHA}"

echo "building image..."
IMAGE=${E2E_IMAGE} ./client/cliente2e/build

echo "test starts..."
go test ./client/cliente2e \
  --e2e-image ${E2E_IMAGE} \
  --kubeconfig ${KUBECONFIG} \
  --namespace ${TEST_NAMESPACE}
