#!/bin/sh

set -o errexit
set -o nounset

: ${TEST_NAMESPACE:?"Need to set TEST_NAMESPACE"}

# Run e2e tests 
/bin/etcd-operator-e2e -test.timeout 30m -test.failfast -test.parallel 4 --namespace=${TEST_NAMESPACE}
