apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  etcdEndpoints: [<etcd-cluster-endpoints>]
  storageType: S3
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: <full-s3-path>
    awsSecret: <aws-secret>
    ## endpoint configures custom (non-aws) s3 endpoint
    #endpoint: https://play.minio.io:9000
    ## forcePathStyle, if set to true, forces s3 requests to use path style addressing
    ## (host/bucket instead of bucket.host)
    #forcePathStyle: true