#!/usr/bin/env bash

# This script is meant to be run inside the test-pod(see test/pod/test-pod.yaml)

set -o errexit
set -o nounset
set -o pipefail

: ${TEST_NAMESPACE:?"Need to set TEST_NAMESPACE"}
: ${OPERATOR_IMAGE:?"Need to set OPERATOR_IMAGE"}
: ${TEST_S3_BUCKET:?"Need to set TEST_S3_BUCKET"}

export PARALLEL_TEST="true"

# The bucket name and aws secret can be set through the pod envs
export TEST_AWS_SECRET=${TEST_AWS_SECRET:-"aws-secret"}

# Try to create TEST_AWS_SECRET if not already present in the namespace
if kubectl -n $TEST_NAMESPACE get secret ${TEST_AWS_SECRET} > /dev/null 2>&1;
then
	echo "Using existing TEST_AWS_SECRET: ${TEST_AWS_SECRET}"
else
	# Try to create the secret from credential and config files at the expected paths
	echo "TEST_AWS_SECRET: ${TEST_AWS_SECRET} not found. Attempting to create."
	AWS_CREDENTIAL="_test/aws/credentials"
	AWS_CONFIG="_test/aws/config"
	kubectl -n ${TEST_NAMESPACE} create secret generic ${TEST_AWS_SECRET} --from-file=${AWS_CREDENTIAL} --from-file=${AWS_CONFIG}
fi

function e2e_pass {
	E2E_TEST_SELECTOR=${E2E_TEST_SELECTOR:-.*}
	go test "./test/e2e/" -run "$E2E_TEST_SELECTOR" -timeout 30m \
	--operator-image $OPERATOR_IMAGE \
	--namespace ${TEST_NAMESPACE}
}

function e2eslow_pass {
	E2E_TEST_SELECTOR=${E2E_TEST_SELECTOR:-.*}
	go test "./test/e2e/e2eslow" -run "$E2E_TEST_SELECTOR" -timeout 30m \
		--operator-image $OPERATOR_IMAGE \
		--namespace ${TEST_NAMESPACE}
}

for p in $PASSES
do
	echo "running ${p} tests"
	${p}_pass
done

echo "test success ==="
