#!/usr/bin/env bash
#
# This script is used for fmt_pass and unit_pass

set -o errexit
set -o nounset
set -o pipefail

export CODECOV_TOKEN=$(cat $CODECOV_TOKEN_FILE)

function finish {
  sudo chown -R "$(whoami)" ./
}
trap finish EXIT

hack/ci/get_dep
hack/test
