apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdRestore"
metadata:
  # An EtcdCluster with the same name will be created
  name: restored-etcd-cluster
spec:
  clusterSpec:
    size: 3
    version: "3.1.8"
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "etcd-snapshot-bucket/v1/default/example-etcd-cluster/3.1.8_0000000000000001_etcd.backup"
    path: <full-s3-path>
    awsSecret: <aws-secret>
